[versions]
lombok = "1.18.36"
annotations = "26.0.1"

junitBom = "5.10.0"
log4j2 = "2.24.1"

[plugins]

[libraries]
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
log4j2 = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j2" }
log4j2-simple = { group = "org.apache.logging.log4j", name = "log4j-slf4j2-impl", version.ref = "log4j2" }

# testing
junitBom = { group = "org.junit", name = "junit-bom", version.ref = "junitBom" }
junit = { group = "org.junit.jupiter", name = "junit-jupiter" }
junitEngine = { group = "org.junit.platform", name = "junit-platform-suite-engine"  }

[bundles]
utils = ["lombok", "annotations"]
testing = ["junit", "junitEngine", "log4j2-simple"]
