[versions]
lombok = "1.18.36"
annotations = "26.0.1"

[plugins]

[libraries]
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

[bundles]
utils = ["lombok", "annotations"]
