[versions]
lombok = "1.18.36"
annotations = "26.0.1"
jline = "3.27.1"
junitBom = "5.10.0"
log4j2 = "2.24.1"
netline = "1.0.2-SNAPSHOT"
netty5 = "5.0.0.Alpha5"
gson = "2.11.0"

[plugins]

[libraries]
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
log4j2 = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j2" }
log4j2-simple = { group = "org.apache.logging.log4j", name = "log4j-slf4j2-impl", version.ref = "log4j2" }
jline = { group = "org.jline", name = "jline", version.ref = "jline" }
junitBom = { group = "org.junit", name = "junit-bom", version.ref = "junitBom" }
junit = { group = "org.junit.jupiter", name = "junit-jupiter" }
junitEngine = { group = "org.junit.platform", name = "junit-platform-suite-engine"  }
netline = { group = "dev.httpmarco", name = "netline", version.ref = "netline"  }
netty5 = { group = "io.netty", name = "netty5-all", version.ref = "netty5" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

[bundles]
utils = ["lombok", "annotations"]
testing = ["junit", "junitEngine", "log4j2-simple"]
