[metadata]
version = "1.0"

[versions]
# Logging
slf4j = "2.0.16"
log4j = "2.24.3"

# Code quality
annotations = "26.0.2"

# configuration
gson = "2.12.1"

# terminal
jline = "3.29.0"

# Networking
grpc = "1.69.0"

[libraries]
# Logging
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
log4j = { module = "org.apache.logging.log4j:log4j-api", version.ref = "log4j" }
log4j-sl4j-impl = { module = "org.apache.logging.log4j:log4j-slf4j-impl", version.ref = "log4j" }

# Code quality
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }

# configuration
gson =  { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

# terminal
jline = { module = "org.jline:jline", version.ref = "jline" }
jline-jansi = { module = "org.jline:jline-terminal-jansi", version.ref = "jline" }

# Networking
grpc-netty =  { group = "io.grpc", name = "grpc-netty-shaded", version.ref = "grpc" }
grpc-protobuf =  { group = "io.grpc", name = "grpc-protobuf", version.ref = "grpc" }
grpc-stub =  { group = "io.grpc", name = "grpc-stub", version.ref = "grpc" }

[bundles]
logging = ["slf4j", "log4j"]
grpc = ["grpc-netty", "grpc-protobuf", "grpc-stub"]