name: Build Image with Docker

on:
  push:

jobs:
  build:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Gradle dependencies cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Launcher with Gradle
        run: ./gradlew :launcher:build

      - name: Login to GHCR
        env:
          DOCKER_USERNAME: httpmarco
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: echo $DOCKER_PASSWORD | docker login ghcr.io --username $DOCKER_USERNAME --password-stdin

      - name: Build & Tag
        run: docker build -f docker/Dockerfile -t ghcr.io/httpmarco/polocloud:latest .

      - name: Push Image to GHCR (latest)
        run: docker push ghcr.io/httpmarco/polocloud:latest
